name = "lako-services"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"

[vars]
LAKO_BOT_API_URL = "https://bot.lako.services"

[observability]
enabled = true
